### PR TITLE
Adds translation of selenocysteine

### PR DESCRIPTION
**Pull request by courcelm**

### CODE REVIEW

**Comment by tariqdaouda** [comment]
Thanks!
Could you just confirm that replacing:

`selenocysteine = rf.Primitive()`
by
`selenocysteine = rf.RList()`

Still works?

Setting it as a primitive will pickle the list and can result in slower perfs

**Comment by courcelm** [comment]
I will try it next week. How an rf.RList() is stored compared to a primitive? Do I need to initialize rf.RList() and use append? Is store.transcripts[transId].set required?  

I could not found documentation for how to use rf.RList() and store?

**Comment by tariqdaouda** [comment]
I never had the time to write a proper documentation for RabaDB, sorry about that.
Once you've declared it, you should be able to use it as a python list (append/extend)
RLists are stored into separate tables instead of being serialized.

**Comment by courcelm** [comment]
Every time I use append/extend it is automatically stored?

**Comment by tariqdaouda** [comment]
No only when you call save on the object.

**Comment by courcelm** [comment]
Here is the result of my test:

Here the code changes:
Transcript.py:
selenocysteine = rf.RList()

importation/Genomes.py:
store.transcripts[transId].selenocysteine.append(start)


I get this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyGeno\importation\Genomes.py", line 179, in importGenome
    chros = _importGenomeObjects(gtfFile, chromosomeSet, genome, batchSize, verbose)
  File "pyGeno\importation\Genomes.py", line 413, in _importGenomeObjects
    store.batch_save()
  File "pyGeno\importation\Genomes.py", line 220, in batch_save
    c.save()
  File "pyGeno\pyGenoObjectBases.py", line 37, in save
    Raba.save(self)
  File "Y:\Anaconda3\envs\pps\lib\site-packages\rabaDB\Raba.py", line 559, in save
    v._save()
  File "Y:\Anaconda3\envs\pps\lib\site-packages\rabaDB\Raba.py", line 886, in _save
    values.append((self.anchorObj.raba_id, e, RabaFields.RABA_FIELD_TYPE_IS_PRIMITIVE), None, None, None)
TypeError: append() takes exactly one argument (4 given)

**Comment by tariqdaouda** [comment]
Fixed, parenthesis was on the wrong place

**Comment by courcelm** [comment]
I changed selenocysteine field to RList. PyGeno now requires rabadb commit 2675a201a1a890a1163fef005ac578aad2af77dc.

**Comment by courcelm** [comment]
@tariqdaouda  Can you push out a new rabaDB release so we can update pygeno setup.py and close this pull request?

**Comment by tariqdaouda** [comment]
Merged

**Pull request merged**
