### PR TITLE
Updating find and findAll with KMP

### PR DESCRIPTION
**Pull request by Kejia**
The _find_ and _findAll_ functions are updated with _KMP-searching_. _cProfile_ is used to check the benchmark (search a 4-length needle in a randomly-generated 8192-length haystack), and the result shows a dramatic performance improvement (_find_ and _findAll_ are the new implementation, and _findByBiSearch_ and _findAllByBiSearch_ are the old one):

| find | findByBiSearch | findAll | findAllByBiSearch |
| ---------------- | ---------------- | ---------------- | ---------------- |
| 0.077 s | 0.242 s | 5.674 s | 25.154 s |

> $ python pyGeno/tools/BinarySequence.py 
> 

> find:
> 
>          133124 function calls (132612 primitive calls) in 0.077 seconds
> 
>    Ordered by: standard name
> 
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>         1    0.000    0.000    0.077    0.077 <string>:1(<module>)
>       512    0.015    0.000    0.016    0.000 BinarySequence.py:197(_kmp_construct_next)
>       512    0.038    0.000    0.070    0.000 BinarySequence.py:209(_kmp_search_first)
>       512    0.004    0.000    0.005    0.000 BinarySequence.py:21(encode)
>       512    0.001    0.000    0.071    0.000 BinarySequence.py:236(_kmp_find)
>       512    0.001    0.000    0.077    0.000 BinarySequence.py:253(find)
>       512    0.000    0.000    0.000    0.000 BinarySequence.py:320(__len__)
>     38912    0.007    0.000    0.007    0.000 BinarySequence.py:323(__getitem__)
>         1    0.000    0.000    0.077    0.077 BinarySequence.py:395(testFind)
>     40960    0.005    0.000    0.005    0.000 {bin}
> 47616/47104    0.004    0.000    0.004    0.000 {len}
>      2048    0.001    0.000    0.001    0.000 {method 'append' of 'array.array' objects}
>         1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
>       513    0.000    0.000    0.000    0.000 {range}
> 
> 
> findAll:
> 
>          12638212 function calls in 5.674 seconds
> 
>    Ordered by: standard name
> 
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>         1    0.000    0.000    5.674    5.674 <string>:1(<module>)
>       512    0.017    0.000    0.018    0.000 BinarySequence.py:197(_kmp_construct_next)
>       512    0.006    0.000    0.007    0.000 BinarySequence.py:21(encode)
>       512    4.132    0.008    5.647    0.011 BinarySequence.py:221(_kmp_search_all)
>       512    0.018    0.000    5.665    0.011 BinarySequence.py:236(_kmp_find)
>       512    0.001    0.000    5.673    0.011 BinarySequence.py:258(findAll)
>   4203008    0.653    0.000    0.653    0.000 BinarySequence.py:323(__getitem__)
>         1    0.001    0.001    5.674    5.674 BinarySequence.py:403(testFindAll)
>   4204544    0.501    0.000    0.501    0.000 {bin}
>   4210688    0.342    0.000    0.342    0.000 {len}
>      2048    0.001    0.000    0.001    0.000 {method 'append' of 'array.array' objects}
>     14848    0.001    0.000    0.001    0.000 {method 'append' of 'list' objects}
>         1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
>       513    0.001    0.000    0.001    0.000 {range}
> 
> 
> findByBiSearch:
> 
>          625668 function calls (465412 primitive calls) in 0.242 seconds
> 
>    Ordered by: standard name
> 
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>         1    0.000    0.000    0.242    0.242 <string>:1(<module>)
> 79872/512    0.146    0.000    0.236    0.000 BinarySequence.py:166(_dichFind)
>       512    0.004    0.000    0.005    0.000 BinarySequence.py:21(encode)
>       512    0.001    0.000    0.241    0.000 BinarySequence.py:241(findByBiSearch)
>     80896    0.024    0.000    0.032    0.000 BinarySequence.py:320(__len__)
>     10752    0.003    0.000    0.003    0.000 BinarySequence.py:323(__getitem__)
>         1    0.000    0.000    0.242    0.242 BinarySequence.py:399(testFindByBiSearch)
> 451072/370176    0.063    0.000    0.088    0.000 {len}
>      2048    0.001    0.000    0.001    0.000 {method 'append' of 'array.array' objects}
>         1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
>         1    0.000    0.000    0.000    0.000 {range}
> 
> 
> findAllByBiSearch:
> 
>          65719812 function calls (48913412 primitive calls) in 25.154 seconds
> 
>    Ordered by: standard name
> 
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>         1    0.000    0.000   25.154   25.154 <string>:1(<module>)
> 8402432/512   15.628    0.000   25.144    0.049 BinarySequence.py:166(_dichFind)
>       512    0.006    0.000    0.007    0.000 BinarySequence.py:21(encode)
>       512    0.001    0.000   25.153    0.049 BinarySequence.py:246(findAllByBiSearch)
>   8404480    2.581    0.000    3.315    0.000 BinarySequence.py:320(__len__)
>   1369600    0.295    0.000    0.295    0.000 BinarySequence.py:323(__getitem__)
>         1    0.001    0.001   25.154   25.154 BinarySequence.py:407(testFindAllByBiSearch)
> 47524864/39120384    6.638    0.000    9.219    0.000 {len}
>      2048    0.001    0.000    0.001    0.000 {method 'append' of 'array.array' objects}
>     15360    0.003    0.000    0.003    0.000 {method 'append' of 'list' objects}
>         1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
>         1    0.000    0.000    0.000    0.000 {range}

### CODE REVIEW

**Comment by tariqdaouda** [comment]
Indeed that's some dramatic improvement. Let me check that there are no conflicts with anything else and I'll merge it.

**Comment by tariqdaouda** [comment]
I've ran the tests and one of them fails with:

**Comment by Kejia** [comment]
Hi @tariqdaouda,

I am not familiar with bioinformatics. The program constructs a data structure based on an alphabet. According to my limited bioinformatics knowledge, the alphabet contains only A, C, G, and T, and later I extended it to N (I saw it as a wildcard in the program), but I think it should include more. So, the bug is that the alphabet doesn't cover the fact, and could you post me the full alphabet list?

**Comment by tariqdaouda** [comment]
Hi @Kejia,
Sure, pyGeno uses the [IUPAC](https://www.bioinformatics.org/sms/iupac.html) notation for nucleotide polymorphisms. It goes from _R_ to _N_, each new letter represents a set possible nucleotides for that position.

You can also find the whole list in the code [here](https://github.com/tariqdaouda/pyGeno/blob/bloody/pyGeno/tools/BinarySequence.py#L283)

Thank you very much for you contribution.

**Comment by Kejia** [comment]
Hi @tariqdaouda,

Thank you for your guide.

I have fixed the bug, and did some micro optimization as well. The benchmark has been updated.

Cheers,
Kejia

**Comment by tariqdaouda** [comment]
Hi @Kejia Kei,

Your pull pull request has been merged. Thanks a lot, your contribution is greatly appreciated!

Cheers,

Tariq

**Comment by Kejia** [comment]
@tariqdaouda: my pleasure :)

**Pull request merged**
