### PR TITLE
Adds translation of mitochondrial proteins

### PR DESCRIPTION
**Pull request by courcelm**
Issue #29

### CODE REVIEW

**Comment by courcelm** [comment]
Any plan/time to merge this soon?

**Comment by tariqdaouda** [comment]
Thanks for this patch. I can't because the checks fail. There's also the compatibility problems issues due to *codonTable* having been renamed *translTable*. I understand the logic behind it, but that breaks all codes using pyGeno that reference *codonTable*. I myself, use *codonTable* as a reference in a lot of my scripts.
If you could create an additional dictionnary *codonTable_mt*  instead that would be great.

**Comment by courcelm** [comment]
Travis had a strange failure but I could not re-run it.

For the codonTable, maybe we can keep an alias  codonTable = translTable[1] . This would not break the code and would allow for more table in the future. Do you agree with this?

**Comment by tariqdaouda** [comment]
Yes that would fix it. Could you change the ids from '1' and '2' to 'default', 'mt' ? To make the table choice more explicit in the code.

**Comment by tariqdaouda** [comment]
Beautiful! Merged, thank you!

**Pull request merged**
